export const RUN_EXPRESS_SRC: string =
  "https://github.com/NasaHack/express-run";

export const FINAL_MESSAGE: string = `RGVhciBGcmllbmRzISBpZiB5b3UgZm91bmQgdGhpcyBoZWxwZnVsIHRoZW4gc3RhciB3aWxsIGJlIGFwcHJlY2lhdGVkIPCfpbAuLiAbXTg7O2h0dHBzOi8vZ2l0aHViLmNvbS9OYXNhSGFjay9ydW4tZXhwcmVzcwfirZAgU3RhciBvbiBHaXRIdWIbXTg7OwcK`;
